# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-29 02:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0002_user_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0, null=True)),
                ('poked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poked', to='poke.User')),
                ('poker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poking', to='poke.User')),
            ],
        ),
    ]
