# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-29 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poke', '0003_poke'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='counter',
        ),
        migrations.AddField(
            model_name='poke',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poke',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
